### ISSUE TITLE
Colorized diff output

### ISSUE THREAD

**Issue by pbrisbin** [freckle/hspec-expectations-json#3]
Should be relatively straight-foreword to add terminal escapes to colorize the diff with red/green as one would expect. There are some open questions though:

- Is it acceptable to just always colorize?
- [If there are cases we shouldn't] how we would implement that conditionality?
- Is checking for a connected `tty` on every single expectation viable?
- How does/could this interact with Hspec's `FORMATTER` argument and its `--[no-]color` option?

**Comment by eborden** [comment]
> Is it acceptable to just always colorize?

You can use the `ansi-terminal` package to detect whether color is appropriate.

> [If there are cases we shouldn't] how we would implement that conditionality?

Once you have the `Bool` everything should flow.

> Is checking for a connected tty on every single expectation viable?

I'd think so. You could be horrible and `unsafePerformIO` into a global variable. However I wouldn't expect it to be significant cost to just check on every expectation.

> How does/could this interact with Hspec's FORMATTER argument and its --[no-]color option?

You'd need to reset the formatting at the start of each output to negate hspec's formatter.

**Comment by eborden** [comment]
https://www.stackage.org/haddock/lts-15.12/hspec-expectations-pretty-diff-0.7.2.5 does has examples.

**Comment by pbrisbin** [comment]
I guess the first three questions were just the third question.

> You'd need to reset the formatting at the start of each output to negate hspec's formatter

That makes sense, to avoid the formatting impacting us. But there's now way to _respect_ the `--[no-]color` option, right?

> [hspec-expectations-pretty-diff-0.7.2.5] has examples

If I understand that code, they've just answered "Yes" to my first open question, thereby side-stepping all the others.

**Comment by pbrisbin** [comment]
```hs
import           Language.Haskell.HsColour hiding (layout)
import           Language.Haskell.HsColour.Colourise (defaultColourPrefs)
import           Language.Haskell.HsColour.ANSI (TerminalType(..))
```

I don't know which ansi escape library is best (I've even written [my own](https://github.com/pbrisbin/escaped)), but I've never used this one.

**Comment by eborden** [comment]
We use `ansi-terminal` in `frontrow-app`.
