### ISSUE TITLE
Lifted expectations

### ISSUE THREAD

**Issue by pbrisbin** [freckle/hspec-expectations-json#4]
By far, our most common uses are in the context of a `yesod-test` spec, in which [`hspec-expectations-lifted`](https://hackage.haskell.org/package/hspec-expectations-lifted) is a huge typing saver. Should we expose lifted assertions too, or leave it to end-users?

```hs
shouldBeJson :: MonadIO m => Value -> Value -> m ()
shouldBeJson a b = liftIO $ a `X.shouldBeJson` b
```

~~If we add this here, is the module `Test.Hspec.Expectations.Json.Lifted` or is it `Test.Hspec.Expectations.Lifted.Json`?~~

`Test.Hspec.Expectations.Json.Lifted`

**Comment by eborden** [comment]
`Test.Hspec.Expectations.Json.Lifted` is my vote.

**Comment by halogenandtoast** [comment]
I agree with `Test.Hspec.Expectations.Json.Lifted`. It feels like the right path of specificity.
